# tells Render how to start app automatically
services:
  - type: web
    name: fyp-mycyberbully
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
